package main

import (
	"fmt"
	"log"
	"time"

	"github.com/NathanBak/easy-cass-go/pkg/easycass"
	"github.com/gocql/gocql"
)

// This example creates a cluster config using properties instead of requiring a Secure Connect
// Bundle zip.  The config is modified (changing the timeout) and then connects to the database and
// prints out the tables in the default keyspace.  Example property values are shown below.  This
// approach is useful when it's easier to pass properties to an application or service than to make
// the file available (such as to code running in containers).

func main() {
	var err error

	// Create the new cluster config
	var cluster *gocql.ClusterConfig
	cluster, err = easycass.NewClusterFromProperties(clientID, clientSecret, hostname, port, keyspace, certPEMBlock, keyPemBlock, pemCerts)
	if err != nil {
		log.Fatal(err)
	}

	// Perform additional cluster configuration as desired (in this case set the Timeout)
	cluster.Timeout = 10 * time.Second

	// Create new session from customized ClusterConfig
	var session *gocql.Session
	session, err = cluster.CreateSession()
	if err != nil {
		log.Fatal(err)
	}

	// This is the default keyspace for the session
	keyspace := cluster.Keyspace

	// Print the tables for the keyspace
	tableNames, err := easycass.GetKeyspaceTableNames(session, keyspace)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("\nKeyspace %q contains the following tables:\n", keyspace)
	for _, tableName := range tableNames {
		fmt.Printf("\t%s\n", tableName)
	}

	session.Close()
}

// These are sample property values.  They should be replaced with real values.  Using the extractprops
// tool is an easy way to obtain the host, port, keyspace, certPEMBlock, keyPemBlock, and pemCerts
// properties.  The clientID and clientSecret can be generated from the Astra web ui.
const (
	clientID     = "KcILqwvnUuseLuwxdkJtRYnB"
	clientSecret = "UvplS_PqKPM0_2YzFP+kg80,mu4btd0tKX5I6e0SaSo_IwafDaP@$$Tcx.kvPcS4UK,z1uMB1wOYfcyZAixo8_T8rui_fj_Rw3l7i-9C2XbFJeepAQAPG5IDxxa8Tx+8"
	hostname     = "fc58c7ce-0f56-435c-acdd-f57cc8ac43d5-us-west-2.db.astra.datastax.com"
	port         = "29083"
	keyspace     = "mykeyspace"
	certPEMBlock = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVQRENDQXlTZ0F3SUJBZ0lDQm5vd0RRWUpLb1pJaHZjTkFRRUxCUUF3ZXpFTE1Ba0dBMVVFQmhNQ1ZWTXgKQ3pBSkJnTlZCQWdUQWtOQk1SUXdFZ1lEVlFRSEV3dFRZVzUwWVNCRGJHRnlZVEVSTUE4R0ExVUVDaE1JUkdGMApZViBJIHdvbmRlcmVkIGlmIGFueW9uZSB3b3VsZCBkZWNvZGUgdGhpcyAuIC4gLiBWUVFERXgxallTNWtZaTVoYzNSeVlTMXdjbTlrCkxtUmhkR0Z6ZEdGNExtTnZiVEFlRncweU1UQTFNVGt4TmpBMk16QmFGdzB6TVRBMU1Ua3hOakEyTXpCYU1JR3AKTVFzd0NRWURWUVFHRXdKVlV6RUxNQWtHQTFVRUNCTUNRMEV4RkRBU0JnTlZCQWNUQzFOaGJuUmhJRU5zWVhKaApkbmMydmVXQUE5RGpubnI3WTVZRy9qZ3hGb1NEbWhqcmxac1lxRUtIU3NrRHlDalQ2MEM4M1B6YTQ0M3I1YXd6CnJROFBzd1JaNDZzVExOVFZGTlkrQzQ1M2NQVkJDZW90M2hsaHVVbldYQ1Jyblk4eUZ3dkFXelUyanpTb1hId2UKYkpsRnJMdGVFZXBKVzBTVjJ1Vnc4T1JRZ3ZwUFlaMDlpSldCMU8reHNNbnNHZ0FRSlpMbTdPL2xkKzY1eUc3MQo3eHJ3NzBQSG10RXZGb0IwNjdScXN5dzM5dUc1Uk1WdkxqOENBd0VBQWFPQm1qQ0JsekFPQmdOVkhROEJBZjhFCkJBTUNCNEF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdJR0NDc0dBUVVGQndNQk1BNEdBMVVkRGdRSEJBVUIKQWdNRUJqQldCZ05WSFJFRVR6Qk5na3RqYkdsbGJuUXVabUkxT1dNM1kyVXRNR1kxTmkwME16VmpMV0ZqWkdRdApaalUzWTJJNVlXSTBNMlExTFhWekxYZGxjM1F0TWk1a1lpNWhjM1J5WVM1a1lYUmhjM1JoZUM1amIyMHdEUVlKCktvWklodmNOQVFFTEJRQURnZ0VCQUxGeEw0WHlScWNTa2JnL0FLblJQeE1kZ1lPTi9sWnd0WVNVK1lYMFNXVVoKWlFIazQrUEprZWZuNWJBcmVpcnEwYW1rNHBwWjNsbm45ZUxPbS8zWXd2NE5ITmVpenpjN001U0VkbmJjSEJwdApJWGpVSytNS1ZkeVljOVE2SVE0Rk8vQVhsdkpvTmNWZm92Ry9LS1duMWZrcVZTaUpISzRGcE5Od3NJemNLRzVoCm5ldG1EY0ZWdUM4a2ZoQUJoRFhjbnlBUzFSbDhuUWxENmJDcTM1Mk1YR1FLcUhHekZJUVR4c0ZuS1pvRDdKRVkKNzRMTzNjVEtXSFNoenY1Q2hzcFBRbUJNRTFHZ093OU1hR21Ia2NrS2Rpd3NzUDNzMzFnbEVVVWRXQm5Ra2QwOQpudlRCNXRxQUN3RndmUGZ6UUZPaWprZGpQSm1YTVhVdWIwSFAyalc3SEh3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
	keyPemBlock  = "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBOGdYQ3RJc2hra0ZWNVB5Y3BOb1dNZ212OUV2L1V0QzJodFRmQlpFamd4b1piSDQyCitLMWhBYnlhL2F2andQU1NTUGlaTU9TSHNpcG1rK0gxcHllQ0p3S1RSdjZQQmQydGF0cS9hUEJCR2hOQWppSXAKVGhpcyB3YXMgb3JpZ2luYWxseSBhIHJlYWwgcHJpdmF0ZSBrZXkgLiAuIC4KRWIwSUJjR2tuZ1ZRSTcyL0U4V3hSZjJjV3cxOVd0VzhjbWNJY1dsVWVxaGpOYW1zZnByUXlOaERXNmdFQmlGdQpIT21PdlJ2WkFvR0JBUGc5bXREM3BMSXk0aFkrUnM5blhiUnFqd25sSVZYbUxjbnliVHBiZ0ZJQkZyNlZBRFQ2ClBLZ1VaQ0tNRVVxM3lpNjFZcjBEbkRCV3grdURvVUtnVE9nYXhLcmxBb0pNRk9kcTBZOGtzcTRCY0FvWXVDcWMKRGo4eW9hS1M5ck5aaEtQNjJVR0NGWG5hQmxXbHliQ2MyQ2NmaDdmWk5DUkx3OURMTjF6TFArY3pBb0dCQVBtVwpaaDc0Y2FNS0dIM01aREdtdGxDVUVwVzhHQ0lDdzVUM0xtQVUxNFF5ckg5R21nYmxRdWRvSGtzNDdtTzVJamgrCjF3d1haZUpQZkxDWVhFV2ViQzhOSU81RU5peHVEU05hR0JSdE1KcFlLL0c1K2dBa0FhWEptbkcyUEN0ajZlbWcKQUVGNkhJa0JpVWhHb1gzeHY4Mkoxa1RLOEJlWW5ycGdOZlJxWkt6RkFvR0FQMzJ5TFNSSnNYSW1OVDQwYWpPcgoyY3N2VG42V0todzNOZUdWWWttbzVsQjArc1d0U2Q5K3lCWi9EZjc1SlQwZ3J4V2hiV3FROWlRYitmYXV0aFc5CjFkZVMyWXE5TzRvdUJvcGhrdFQyQmw5RHdyRlQyVUlVdXNFK2FoQmduTHFXbkVJNmN2RE1nVi9zSXRmR1lDK2QKY1ZRMUtDYWJtWFR2WG1XN2dUWlMzOVVDZ1lFQXIxajl1QVo5OTdpUkNsaDlqL0I3SjlOUDEwakZmNmVIZHZITgo4QXpVZVBrTS9ZSkJsbFNkazJ3djFGTlVFRld4K0JVTXlsN3A0bnhMc3Rub0FiVlNkaC80SWMxa2JnU0hVRzNzCmV2VlhieWhBLzF2VWl5TEEwWlA0NEtqU1R2MnNDY215UkU0aEhCUXJPYzc5aURrK3NvMkRMdU9RbUZOT09NeDkKTzVFLzE2MENnWUJ5SjRiMGNwa1RwTVdRakJIMmEzMk9JRjhxK05hTjRtN3JNYThPZzBva3dWM3J3aFBKV042SgphV2JBZFBvZWpIZ1A0d0I1QXdycFlQUlU1MitsbjNCSk5EVGdHekhzazYvN0ZhVXVtZ253Wk1KeEN1eFZ3cXlPCitOaEd4a21VRkpBT2ZOUk8rK1hGaWc2eHI1aC80OEFBQVE0eTJQcTZxb3N6eHJiME12ZWs3UT09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="
	pemCerts     = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR0RENDQXB5Z0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3ZXpFTE1Ba0dBMVVFQmhNQ1ZWTXgKQ3pBSkJnTlZCQWdUQWtOQk1SUXdFZ1lEVlFRSEV3dFRZVzUwWVNCRGJHRnlZVEVSTUE4R0ExVUVDaE1JUkdGMApZVk4wWVhneERqQU1CZ05WQkFzVEJVTnNiM1ZrTVNZd0pBWURWUVFERXgxallTNWtZaTVoYzNSeVlTMXdjbTlrCkxtUmhkR0Z6ZEdGNExtTnZiVEFlRncweU1UQXhNakF5TURFMk1ESmFGdzB6TVRBeE1qQXlNREUyTURKYU1Ic3gKQ3pBSkJnICBEaWQgeW91IHJlYWxseSBkZWNvZGUgdGhpcz8gIFdlcmUgeW91IGhvcGluZyB0byBnZXQgc29tZXRoaWduIG91dCBvZiBpdD8gICBRMnhoY21FeApFVEFQQmdOVkJBb1RDRVJoZEdGVGRHRjRNUTR3REFZRFZRUUxFd1ZEYkc5MVpERW1NQ1FHQTFVRUF4TWRZMkV1ClpHSXVZWE4wY21FdGNISnZaQzVrWVhSaGMzUmhlQzVqYjIwd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFES09ucHdjTTdIQWFXT3ZuZkJrY0VZTDd3d0J0cHRlTmM0YWNYTTFtVHJvZzI4OUt4ZwpzVVFFZ2RPVDJFZlJpUzNxaHJQYlpuNytlWFlUQTduVDlVWDN4bm5Qd2lnVEFtRVFkUXZmL0FYYTdyK0docEJvCnFvL0NQMEpYRWR0cnRBOEtWRHFXR3hnbm5wVE5XYkZtQkVqQ21HMjk5L2JGZ1dHbWd2QUxqaHdXSEFVeVQzc0gKQXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFWSnc2ZFZUSlVIRzZ5V1VaUHdXZGsxMlJhdUZ4SDkrKwpVQjE2ZnYwd0xOeTc4Qk5ZY1YvVmJOcS9RaHltejlWL1pTTXRtckp3Mi9sVjRpN3RnVk1WRmthTlBFZUZ0SE9MCjBjV0ptVjZ5dUZsV1dHamFaM29IQ0FMOUF3ZzR4NldRbXRNb3JlZGNwUlNBT0duOWhYK0lNZW5SRjRPRUk4bHQKRzE3elZHYU1UaFo3L09IekZJdmdYNXlucWw5c1JCWEcwQWpOc0JHMlFpUCswWGlhOUJHdnZqa3FBZnh3cDQ0QwpXYWNWc2JiV0ZyYytyZVltT2Ztb3k4YjFGbG0vZ1hWUDJEYmpNWXdIWDVSS3ZQdDJTUTdMMmlYZ2FhMWE0K2c5ClpKeC9VM1JGSEtlRmJ3cFJMRkg3MDNGQTFXMjAxMzlNaW1yU2ZpbkhpUVN5K1dFRHM3UDQxdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0="
)
